### ISSUE TITLE
vsphere_virtual_machine "cannot locate virtual machine or template with UUID"

### ISSUE THREAD

**Issue by ephos** [terraform-providers/terraform-provider-vsphere#271]
### Terraform Version

```bash
Terraform v0.11.1
+ provider.vsphere v1.0.1

```

### vSphere Provider Version

```bash
.
└── provider.vsphere ~> 1.0.1
```

### Affected Resource(s)

Data Sources
- `vsphere_virtual_machine`

Resources
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
# Providers
provider "vsphere" {
    version = "~> 1.0.1"
    vsphere_server = "vCenter.domain.local"
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
}

# Data
data "vsphere_datacenter" "dc" {
  name = "MyDataCenter"
}

data "vsphere_datastore" "datastore" {
  name          = "MyDatastore"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "Cluster1/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "vlan_555"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
    name = "Server2012_R2_Template"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# Resources
resource "vsphere_virtual_machine" "server1" {
    name = "${var.vsphere_virtual_machine_name}"
    num_cpus = "${var.vsphere_virtual_machine_vcpu}"
    memory = "${var.vsphere_virtual_machine_memory}"
    resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
    scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
    folder = "My/Vm/Folder"

    cpu_hot_add_enabled = true
    memory_hot_add_enabled = true

    network_interface {
        network_id   = "${data.vsphere_network.network.id}"
        adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
    }

    disk {
        name = "${var.vsphere_virtual_machine_name}.vmdk"
        //size = "${data.vsphere_virtual_machine.template.disk_sizes[0]}"
        size = 50
        thin_provisioned = true
    }

    clone {
        template_uuid = "${data.vsphere_virtual_machine.template.id}"
        
        customize {
            windows_options {
                computer_name = "${var.vsphere_virtual_machine_name}"
                admin_password = "REDACTED"
                join_domain = "domain.local"
                domain_admin_user = "${var.domainjoin_user}"
                domain_admin_password = "${var.domainjoin_password}"
                time_zone = "035"
                organization_name = "Test"
            }

            network_interface {
                ipv4_address = "${var.network_interface_ipv4_address}" 
                ipv4_netmask = 24
                dns_server_list = ["10.1.1.1", "10.1.1.2", "10.1.1.3", "10.1.1.4"]
                dns_domain = "domain.local"
            }

            ipv4_gateway = "10.10.10.50"
        }
    }
}
```

### Debug Output

[DebugGist](https://gist.github.com/ephos/42f49890d15b37d63a7d13e86d45be9b)

### Expected Behavior

The VM template should have been located from its datasource.

### Actual Behavior

The following was displayed

```bash
Error: Error running plan: 1 error(s) occurred:

* vsphere_virtual_machine.server1: 1 error(s) occurred:

* vsphere_virtual_machine.server1: cannot locate virtual machine or template with UUID "421659f0-e810-e754-c31a-5364df597d79": virtual machine with UUID "421659f0-e810-e754-c31a-5364df597d79" not found
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

`terraform apply` 
or
`terraform plan`

### Important Factoids

vSphere version is 5.5 U3.  

### References

NA

**Comment by vancluever** [comment]
Hey @ephos, thanks for the report and sorry you are having trouble. However, I cannot reproduce this on vSphere 5.5 U3f.

Can you tell me a bit more about your setup? Is the user a provisioning user with possibly split privileges? Also, can you tell me a bit of how the template was created and any options that might be affecting the UUID set on the virtual machine, if any?

I attempted to reproduce this using a standalone host (managed by vCenter), and an imported Ubuntu 14.04 template, which was then cloned.

Thanks!

**Comment by RyanD0001** [comment]
Hi @vancluever, I have the same issue as above on vCenter Server 5.5 Update 3e
using terraform windows version v0.11.1

heres my build file

#configure the VMware vSphere Provider
provider "vsphere" {
   
    vsphere_server = "${var.vsphere_vcenter}"
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    allow_unverified_ssl = true
}


data "vsphere_datacenter" "dc" {
  name = ""
}

data "vsphere_datastore" "datastore" {
  name          = "Dev-Trial"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "Dev-Trial"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = ""
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "ryan-clone"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"

}

resource "vsphere_virtual_machine" "vm" {
  name             = "${var.vsphere_winhost}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder = "Dev-T"

  num_cpus = 4
  memory   = 16000
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }


  
  
 disk {
    name = "terraform-test.vmdk"
    size = "100"
  }
  
  
  
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

customize {

      windows_options {
        computer_name = "${var.vsphere_winhost}"
        
      }

      network_interface {}

    }
  }
  }

Thanks

**Comment by ephos** [comment]
Hi @vancluever , I just checked both vCenters that we have that gave me the issue and both were _vCenter Server 5.5 Update 3e_.  In both vCenters there are different templates, I have tried on about 4 different Windows based templates (2 in one vCenter, 2 in the other (2012 R2 and 2016)).  I haven't tried any of our Linux templates.  

I tried with a provisioning user but also saw the same error on a full admin to vCenter.

The Windows templates were basically shell VM's created, ISO installs of Windows and then turned into a template (and booted to patch once a month).

**Comment by vancluever** [comment]
Hey @ephos and @RyanD0001, thanks for the updates.

Not too sure if either of you use has used the MOB before, but I'm wondering if you can try the following on it:

* Drill down to your VM (once in the MOB you can click down to it), and in its `config` verify that `uuid` is set
* Take that UUID, and the top level `ServiceContent` object in the MOB, load the `FindByUuid` method, and enter that UUID in, kind of like what you see here:

![screenshot from 2017-12-06 09-07-08](https://user-images.githubusercontent.com/10704423/33674714-1feaea96-da65-11e7-9687-9b4cab2e3506.png)

After that's done, invoke the method. Let me know if you are able to find the VM this way.

If that doesn't work, can you go back to the VM, locate the `instanceUuid` of the VM, and try the method again, but this time, ensure `instanceUuid` in the method invocation window is set to `true`.

You can find info on the MOB here: https://www.terraform.io/docs/providers/vsphere/index.html#via-the-vsphere-managed-object-browser-mob-

Thanks!

**Comment by ephos** [comment]
@vancluever I hadn't used the MOB before, thanks for showing me this (coming from the PowerCLI world a lot of this is abstracted).  Anyway I did as you instructed, sure enough I wasn't able to return any data for the template in question, either by _instanceUuid_ or _uuid_.

One thing though, if I convert the template back to a VM both of these queries work.  Perhaps something with 5.5U3e on querying a template by by _instanceUuid_ or _uuid_?

**Comment by vancluever** [comment]
@ephos this is interesting data - thank you for checking!

I also see something [here](https://communities.vmware.com/thread/400607) that at some point in time in the past, `FindByUuid` actually did _not_ work on templates.

I did not necessarily test VMs marked as templates on our 5.5f installation, I'll try that and report back the results.

Thanks!

**Comment by vancluever** [comment]
@ephos confirmed that this is still an issue in 5.5f. Looks like the best workaround for now is to convert specific templates to virtual machines.

I'm guessing we will need to think of a different way to hunt down UUIDs for templates as a fallback - I'll have to think of the best way to do that would be. I don't necessarily want to do managed object references for VMs as we have committed to using UUIDs as a the `id` attribute going forward, so I'd like that consistent across the provider.

Will update when I have something here.

Sorry for the trouble!

**Comment by ephos** [comment]
@vancluever no worries, I knew it might be a little tough being on 5.5 as we are a little behind upgrading, we are planning on upgrading to 6.5 soon though so that should fix it, a work around could be perhaps cloning the template and turning that into a virtual machine.  Thanks for the help!

**Comment by vancluever** [comment]
@ephos no problem :slightly_smiling_face:

Remember too that a template is mainly just a VM that has been marked as such and hasn't been assigned to a host/cluster/resource pool. So all the functionality from a clone perspective will be the same, it just might have a slight impact to your resource count due to the fact that it's present in a powered off state on one of your hosts.

Anyway will update when I have more details on the fix!

**Comment by RyanD0001** [comment]
@vancluever this is the uuid of my template:

Get-Template ryan-clone | %{(Get-View $_.Id).config.uuid}
4229d461-8419-42cc-87f5-aa43b936f784

and this is the error on terraform:

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_network.network: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: cannot locate virtual machine or template with UUID "4229d461-8419-42cc-87f5-aa43b936f784"
: virtual machine with UUID "4229d461-8419-42cc-87f5-aa43b936f784" not found

Thanks,

Ryan

**Comment by joppa27** [comment]
@ephos I had the same error when I upgraded to the `1.1.0` vsphere provider and I'm on `vSphere 6.0`.
For me it turned out to be an issue with my remote_state file. On a recommendation from @jwieringa I deleted the remote state file and that got rid of the `uuid` not found error.

**Comment by maxadamo** [comment]
it seems to be working with plugin 1.1.1 (a side note: I still don't know how to browse/list the plugin version)

**Comment by den-is** [comment]
I have same issue on vSphere 5.5
plugin version 1.2.0

**Comment by Lucius-** [comment]
We're also running into the same issue. It doesn't matter if the template we're using is marked as a template or not. We have no issues locating the VM or template (by UUID or otherwise) via PowerCLI tools, the `govc` binary or via the MOB.

Issue occurs on both  v1.1.1 and 1.2.0 of the plugin. We're running vSphere Version 6.0.0 Build 5318172

I've attached the output of TF_LOG=DEBUG, hope that helps!

[debug.txt](https://github.com/terraform-providers/terraform-provider-vsphere/files/1627267/debug.txt)

**Comment by ephos** [comment]
I am seeing the same issue as @Lucius- where even with the template converted to a virtual machine its stll throwing the `* vsphere_virtual_machine.vm: cannot locate virtual machine or template with UUID "4216eeb6-dcee-aae0-5fb2-b1b2c313be72": virtual machine with UUID "4216eeb6-dcee-aae0-5fb2-b1b2c313be72" not found` error.  Latest tests were with version 1.2.0.

**Comment by vancluever** [comment]
Paging @genevievelesperance and @rowanjacobs - was this something you were still planning on working on? Thinking that I want to fast-track this as we are getting more reports.

**Comment by genevievelesperance** [comment]
We are a little strapped for bandwidth on the team right now so we will not be able to get to this anytime soon.

**Comment by vancluever** [comment]
Great thanks for replying @genevievelesperance - I'll take it over based on our discussions in #318.

**Comment by den-is** [comment]
well...upgrade to plugin v1.3.0 wasn't able to fix issue

**Comment by johnjelinek** [comment]
ya, I opened a bug for this upstream: vmware/govmomi#1020. As a workaround, would searching by name instead of UUID (and matching on UUID) work until they fix this upstream?

**Comment by vancluever** [comment]
Hey all, as mentioned, we will be fixing this using a different kind of approach to locating the UUID for a template. Sorry this work has been delayed for so long.

This is not a SDK bug, this is an issue with a (currently undocumented) issue with the API where the call previously did not support searching templates via UUID. You can find more info here: 

We won't be implementing any workarounds that search by name, unfortunately.

Thanks!

**Comment by johnjelinek** [comment]
You're missing the link after `You can find more info here:`. Looks like there's a CLI equivalent workaround, maybe we can implement that workaround in code https://github.com/vmware/govmomi/issues/1020#issuecomment-361323887

**Comment by johnjelinek** [comment]
@vancluever: looks like this code implementation could help here: https://github.com/vmware/govmomi/issues/1020#issuecomment-361333460 What do you think?

**Comment by vancluever** [comment]
Hey @johnjelinek, indeed this is the method we will be using - this was documented in #318 as well. We have used this method for searching other MO's (namely networks). It will be implemented as a fallback method for vSphere versions previous to a specific version so that we can continue to use more direct calls on versions that support it.

Thanks!

**Comment by nowhammies** [comment]
Just in case you missed it from #318 

I am experiencing this behavior is 6.0 as well

Name: VMware vCenter Server
Vendor: VMware, Inc.
Version: 6.0.0
Build: 5318203
OS type: linux-x64
API type: VirtualCenter
API version: 6.0
Product ID: vpx
UUID: 15d87409-30cd-4865-9b65-437022dca8d7

**Comment by maxadamo** [comment]
@vancluever regression? Is it possible that this happens again with plugin version 1.3.3 ?

**Comment by vancluever** [comment]
Hey @maxadamo, if you can open a new issue with your details that would be great.

The VM search code has not changed, so it might be unrelated. You can see the history of the helper code [here](https://github.com/terraform-providers/terraform-provider-vsphere/commits/master/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go).

Thanks!
